import Head from "next/head";
export default function Header({ title }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>
    </div>
  );
}
